import tkinter as tk
import tkinter.ttk as ttk
from PIL import Image, ImageTk

top = tk.Tk()
top.geometry("524x276")
top.resizable(0,0)
top.title("À Propos")
top.configure(background="#d9d9d9")

# Read the Image
image = Image.open("AppImg/Ext/paypal.png")
# Resize the image using resize() method
resize_image = image.resize((100, 30))
img = ImageTk.PhotoImage(resize_image)

try :
    top.iconbitmap("AppImg/Win/.ico/AboutLogo.ico")
except :
    pass

media = tk.PhotoImage(file="AppImg/Ext/MediaFireBanner.png")
snapchat_acc = tk.PhotoImage(file="AppImg/Social/snapchat.png")
gmail_acc = tk.PhotoImage(file="AppImg/Social/gmail.png")
discord_acc = tk.PhotoImage(file="AppImg/Social/discord.png")
git_acc = tk.PhotoImage(file="AppImg/Social/github.png")
 
PayPal = tk.Button(top)
PayPal.place(relx=0.405, rely=0.812, height=30, width=100)
PayPal.configure(activebackground="#d9d9d9", image=img, relief="flat", bd=0, cursor="@AdditionalCursors/pointer.cur")
PayPal.configure(activeforeground="black")
PayPal.configure(background="#d9d9d9")
PayPal.configure(compound='left')
PayPal.configure(disabledforeground="#a3a3a3")
PayPal.configure(foreground="#000000")
PayPal.configure(highlightbackground="#d9d9d9")
PayPal.configure(highlightcolor="black")
PayPal.configure(pady="0")

TSeparator1 = ttk.Separator(top)
TSeparator1.place(relx=0.309, rely=0.728,relwidth=0.382)
 
GitHub = tk.Button(top)
GitHub.place(relx=0.313, rely=0.808, height=32, width=32)
GitHub.configure(activebackground="#d9d9d9")
GitHub.configure(activeforeground="black")
GitHub.configure(background="#d9d9d9")
GitHub.configure(compound='left')
GitHub.configure(disabledforeground="#a3a3a3")
GitHub.configure(foreground="#000000")
GitHub.configure(highlightbackground="#d9d9d9")
GitHub.configure(highlightcolor="black")
GitHub.configure(pady="0")
GitHub.configure(text=None, cursor="@AdditionalCursors/pointer.cur", bd=0, relief="flat", image=git_acc)
Snapchat = tk.Button(top)
Snapchat.place(relx=0.221, rely=0.808, height=32, width=32)
Snapchat.configure(activebackground="#d9d9d9", cursor="@AdditionalCursors/pointer.cur")
Snapchat.configure(activeforeground="black")
Snapchat.configure(background="#d9d9d9")
Snapchat.configure(compound='left', relief="flat", bd=0)
Snapchat.configure(disabledforeground="#a3a3a3")
Snapchat.configure(foreground="#000000")
Snapchat.configure(highlightbackground="#d9d9d9")
Snapchat.configure(highlightcolor="black")
Snapchat.configure(pady="0")
Snapchat.configure(text=None, image=snapchat_acc)
Discord = tk.Button(top)
Discord.place(relx=0.628, rely=0.808, height=32, width=32)
Discord.configure(activebackground="#d9d9d9")
Discord.configure(activeforeground="black")
Discord.configure(background="#d9d9d9")
Discord.configure(compound='left')
Discord.configure(disabledforeground="#a3a3a3")
Discord.configure(foreground="#000000")
Discord.configure(highlightbackground="#d9d9d9")
Discord.configure(highlightcolor="black")
Discord.configure(pady="0")
Discord.configure(text=None, cursor="@AdditionalCursors/pointer.cur", bd=0, image=discord_acc)
Gmail = tk.Button(top)
Gmail.place(relx=0.719, rely=0.808, height=32, width=32)
Gmail.configure(activebackground="#d9d9d9", cursor="@AdditionalCursors/pointer.cur")
Gmail.configure(activeforeground="black")
Gmail.configure(background="#d9d9d9")
Gmail.configure(compound='left')
Gmail.configure(disabledforeground="#a3a3a3")
Gmail.configure(foreground="#000000")
Gmail.configure(highlightbackground="#d9d9d9")
Gmail.configure(highlightcolor="black", relief="flat", bd=0, image=gmail_acc)
Gmail.configure(pady="0")
Gmail.configure(text=None)
PresentationPt1 = tk.Label(top)
PresentationPt1.place(relx=0.086, rely=0.076, height=21, width=434)
PresentationPt1.configure(activebackground="#f9f9f9")
PresentationPt1.configure(background="#d9d9d9")
PresentationPt1.configure(compound='left')
PresentationPt1.configure(disabledforeground="#a3a3a3")
PresentationPt1.configure(font="-family {Yu Gothic UI} -size 9")
PresentationPt1.configure(foreground="#000000")
PresentationPt1.configure(highlightbackground="#d9d9d9")
PresentationPt1.configure(highlightcolor="black")
PresentationPt1.configure(text='''AutoBulletin est une application permettant au professeur l'utilisant de générer''')
PresentationPt2 = tk.Label(top)
PresentationPt2.place(relx=0.086, rely=0.145, height=21, width=434)
PresentationPt2.configure(activebackground="#f9f9f9")
PresentationPt2.configure(background="#d9d9d9")
PresentationPt2.configure(compound='left')
PresentationPt2.configure(disabledforeground="#a3a3a3")
PresentationPt2.configure(font="-family {Yu Gothic UI} -size 9")
PresentationPt2.configure(foreground="#000000")
PresentationPt2.configure(highlightbackground="#d9d9d9")
PresentationPt2.configure(highlightcolor="black")
PresentationPt2.configure(text='''et d'écrire une appréciation sur le bulletin Pronote™ de l'élève.''')
InfoFrame = tk.Frame(top)
InfoFrame.place(relx=0.086, rely=0.272, relheight=0.38
, relwidth=0.41)
InfoFrame.configure(relief='groove')
InfoFrame.configure(borderwidth="2")
InfoFrame.configure(relief="groove")
InfoFrame.configure(background="#d9d9d9")
InfoFrame.configure(highlightbackground="#d9d9d9")
InfoFrame.configure(highlightcolor="black")
InfoLabel = tk.Label(InfoFrame)
InfoLabel.place(relx=0.163, rely=0.076, height=21, width=144)
InfoLabel.configure(activebackground="#f9f9f9")
InfoLabel.configure(background="#d9d9d9")
InfoLabel.configure(compound='left')
InfoLabel.configure(disabledforeground="#a3a3a3")
InfoLabel.configure(font="-family {Yu Gothic UI} -size 9")
InfoLabel.configure(foreground="#000000")
InfoLabel.configure(highlightbackground="#d9d9d9")
InfoLabel.configure(highlightcolor="black")
InfoLabel.configure(text='''Informations''')
PythonVerLabelGrv = tk.Label(InfoFrame)
PythonVerLabelGrv.place(relx=-0.023, rely=0.352, height=21
, width=144)
PythonVerLabelGrv.configure(activebackground="#f9f9f9")
PythonVerLabelGrv.configure(anchor='w')
PythonVerLabelGrv.configure(background="#d9d9d9")
PythonVerLabelGrv.configure(compound='left')
PythonVerLabelGrv.configure(disabledforeground="#a3a3a3")
PythonVerLabelGrv.configure(foreground="#000000")
PythonVerLabelGrv.configure(highlightbackground="#d9d9d9")
PythonVerLabelGrv.configure(highlightcolor="black")
PythonVerLabelGrv.configure(relief="groove")
PythonVerLabelGrv.configure(text='''→ Python 3.10.8''')
GitPrjLabelGrv = tk.Label(InfoFrame)
GitPrjLabelGrv.place(relx=-0.023, rely=0.705, height=21, width=144)
GitPrjLabelGrv.configure(activebackground="#f9f9f9")
GitPrjLabelGrv.configure(anchor='w')
GitPrjLabelGrv.configure(background="#d9d9d9")
GitPrjLabelGrv.configure(compound='left')
GitPrjLabelGrv.configure(disabledforeground="#a3a3a3")
GitPrjLabelGrv.configure(foreground="#000000")
GitPrjLabelGrv.configure(highlightbackground="#d9d9d9")
GitPrjLabelGrv.configure(highlightcolor="black")
GitPrjLabelGrv.configure(relief="groove")
GitPrjLabelGrv.configure(text='''→ GitHub du projet''')
LicenceLabelFlt = tk.Label(InfoFrame)
LicenceLabelFlt.place(relx=-0.023, rely=0.533, height=21, width=144)
 
LicenceLabelFlt.configure(activebackground="#f9f9f9")
LicenceLabelFlt.configure(anchor='w')
LicenceLabelFlt.configure(background="#d9d9d9")
LicenceLabelFlt.configure(compound='left')
LicenceLabelFlt.configure(disabledforeground="#a3a3a3")
LicenceLabelFlt.configure(foreground="#000000")
LicenceLabelFlt.configure(highlightbackground="#d9d9d9")
LicenceLabelFlt.configure(highlightcolor="black")
LicenceLabelFlt.configure(text='''→ Licence''')
Frame1_1 = tk.Frame(top)
Frame1_1.place(relx=0.504, rely=0.272, relheight=0.38
, relwidth=0.41)
Frame1_1.configure(relief='groove')
Frame1_1.configure(borderwidth="2")
Frame1_1.configure(relief="groove")
Frame1_1.configure(background="#d9d9d9")
Frame1_1.configure(highlightbackground="#d9d9d9")
Frame1_1.configure(highlightcolor="black")

Button1 = tk.Button(Frame1_1, image=media)
Button1.place(relx=0.085, rely=0.667, height=24, width=167)
Button1.configure(background="#d9d9d9", activebackground="#d9d9d9", cursor="@AdditionalCursors/pointer.cur")
Button1.configure(pady="0")
Button1.configure(relief="flat", bd=0)

OutsFrmName = tk.Label(top)
OutsFrmName.place(relx=0.599, rely=0.308, height=21, width=174)
OutsFrmName.configure(activebackground="#f9f9f9")
OutsFrmName.configure(anchor='w')
OutsFrmName.configure(background="#d9d9d9")
OutsFrmName.configure(compound='left')
OutsFrmName.configure(disabledforeground="#a3a3a3")
OutsFrmName.configure(foreground="#000000")
OutsFrmName.configure(highlightbackground="#d9d9d9")
OutsFrmName.configure(highlightcolor="black")
OutsFrmName.configure(relief="groove")
OutsFrmName.configure(text='''LABARBE Léo, Mr Imloul ←''')
OutsFrmMail = tk.Label(top)
OutsFrmMail.place(relx=0.5, rely=0.399, height=21, width=174)
OutsFrmMail.configure(activebackground="#f9f9f9")
OutsFrmMail.configure(anchor='w')
OutsFrmMail.configure(background="#d9d9d9")
OutsFrmMail.configure(compound='left')
OutsFrmMail.configure(disabledforeground="#a3a3a3")
OutsFrmMail.configure(foreground="#000000")
OutsFrmMail.configure(highlightbackground="#d9d9d9")
OutsFrmMail.configure(highlightcolor="black")
OutsFrmMail.configure(relief="groove")
OutsFrmMail.configure(text='''→ labarbe.leo2308@gmail.com''')
top.mainloop()