import tkinter as tk
import tkinter.ttk as ttk

top = tk.Tk()
top.geometry("495x501")
top.resizable(0,0)
top.title("À Propos")
top.configure(background="#d9d9d9", cursor="@AdditionalCursors/default.cur")
top.iconbitmap("AppImg/win/.ico/AboutLogo.ico")
 
InfRelAppLabel = tk.Label(top)
InfRelAppLabel.place(relx=0.04, rely=0.026, height=21, width=324)
InfRelAppLabel.configure(activebackground="#f9f9f9")
InfRelAppLabel.configure(anchor='w')
InfRelAppLabel.configure(background="#d9d9d9")
InfRelAppLabel.configure(compound='left')
InfRelAppLabel.configure(disabledforeground="#a3a3a3")
InfRelAppLabel.configure(foreground="#000000")
InfRelAppLabel.configure(highlightbackground="#d9d9d9")
InfRelAppLabel.configure(highlightcolor="black")
InfRelAppLabel.configure(text='''Informations relatives à l'application''')

TitleSepContentRelApp = ttk.Separator(top)
TitleSepContentRelApp.place(relx=0.046, rely=0.092, relwidth=0.788)

logo = tk.PhotoImage(file="AppImg/win/.png/WinSquared_100x100.png")
mail = tk.PhotoImage(file="AppImg/Social/gmail.png")
snap = tk.PhotoImage(file="AppImg/Social/snapchat.png")
inst = tk.PhotoImage(file="AppImg/Social/instagram.png")
payp = tk.PhotoImage(file="AppImg/Ext/paypal-(-65).png")

AppLogoContainer = tk.Label(top)
AppLogoContainer.place(relx=0.069, rely=0.132, height=104, width=104)
AppLogoContainer.configure(activebackground="#f9f9f9")
AppLogoContainer.configure(anchor='w')
AppLogoContainer.configure(background="#d9d9d9")
AppLogoContainer.configure(compound='left')
AppLogoContainer.configure(foreground="#000000")
AppLogoContainer.configure(relief="groove")
AppLogoContainer.configure(text=None, image=logo)

AppName = tk.Label(top)
AppName.place(relx=0.303, rely=0.174, height=21, width=204)
AppName.configure(activebackground="#f9f9f9")
AppName.configure(anchor='w')
AppName.configure(background="#d9d9d9")
AppName.configure(compound='left')
AppName.configure(disabledforeground="#a3a3a3")
AppName.configure(font="-family {Yu Gothic UI} -size 11 -weight bold")
AppName.configure(foreground="#000000")
AppName.configure(highlightbackground="#d9d9d9")
AppName.configure(highlightcolor="black")
AppName.configure(text='''AutoBulletin''')

AppVers = tk.Label(top)
AppVers.place(relx=0.301, rely=0.212, height=21, width=84)
AppVers.configure(activebackground="#f9f9f9")
AppVers.configure(anchor='w')
AppVers.configure(background="#d9d9d9")
AppVers.configure(compound='left')
AppVers.configure(disabledforeground="#a3a3a3")
AppVers.configure(foreground="#000000")
AppVers.configure(highlightbackground="#d9d9d9")
AppVers.configure(highlightcolor="black")
AppVers.configure(text='''B.0.2''')

AppCopyrights = tk.Label(top)
AppCopyrights.place(relx=0.299, rely=0.251, height=21, width=164)
AppCopyrights.configure(activebackground="#f9f9f9")
AppCopyrights.configure(anchor='w')
AppCopyrights.configure(background="#d9d9d9")
AppCopyrights.configure(compound='left')
AppCopyrights.configure(disabledforeground="#a3a3a3")
AppCopyrights.configure(foreground="#000000")
AppCopyrights.configure(highlightbackground="#d9d9d9")
AppCopyrights.configure(highlightcolor="black")
AppCopyrights.configure(text='''© LABARBE Léo, Mr Imloul''')

ThxLabel = tk.Label(top)
ThxLabel.place(relx=0.063, rely=0.391, height=21, width=214)
ThxLabel.configure(activebackground="#f9f9f9")
ThxLabel.configure(anchor='w')
ThxLabel.configure(background="#d9d9d9")
ThxLabel.configure(compound='left')
ThxLabel.configure(disabledforeground="#a3a3a3")
ThxLabel.configure(foreground="#000000")
ThxLabel.configure(highlightbackground="#d9d9d9")
ThxLabel.configure(highlightcolor="black")
ThxLabel.configure(text='''Remerciments''')

Cursors = tk.Label(top)
Cursors.place(relx=0.121, rely=0.441, height=21, width=214)
Cursors.configure(activebackground="#f9f9f9")
Cursors.configure(anchor='w')
Cursors.configure(background="#d9d9d9")
Cursors.configure(compound='left')
Cursors.configure(disabledforeground="#a3a3a3")
Cursors.configure(foreground="#000000")
Cursors.configure(highlightbackground="#d9d9d9")
Cursors.configure(highlightcolor="black")
Cursors.configure(text='''→ Curseurs :''')

CursorsUsername = tk.Label(top)
CursorsUsername.place(relx=0.263, rely=0.441, height=21, width=74)
CursorsUsername.configure(activebackground="#f9f9f9")
CursorsUsername.configure(anchor='w')
CursorsUsername.configure(background="#d9d9d9", cursor="@AdditionalCursors/pointer.cur")
CursorsUsername.configure(compound='left')
CursorsUsername.configure(font="-family {Segoe UI} -size 9 -underline 1")
CursorsUsername.configure(foreground="#5662eb")
CursorsUsername.configure(text='''FlynMaker49''')

Sounds = tk.Label(top)
Sounds.place(relx=0.121, rely=0.487, height=21, width=214)
Sounds.configure(activebackground="#f9f9f9")
Sounds.configure(anchor='w')
Sounds.configure(background="#d9d9d9")
Sounds.configure(compound='left')
Sounds.configure(disabledforeground="#a3a3a3")
Sounds.configure(foreground="#000000")
Sounds.configure(highlightbackground="#d9d9d9")
Sounds.configure(highlightcolor="black")
Sounds.configure(text='''→ Sons :''')

SoundsUsername1 = tk.Label(top)
SoundsUsername1.place(relx=0.218, rely=0.487, height=21, width=74)
SoundsUsername1.configure(activebackground="#f9f9f9")
SoundsUsername1.configure(anchor='w')
SoundsUsername1.configure(background="#d9d9d9", cursor="@AdditionalCursors/pointer.cur")
SoundsUsername1.configure(compound='left')
SoundsUsername1.configure(font="-family {Segoe UI} -size 9 -underline 1")
SoundsUsername1.configure(foreground="#5662eb")
SoundsUsername1.configure(text='''Leszek_Szary''')

SoundsUsername2 = tk.Label(top)
SoundsUsername2.place(relx=0.218, rely=0.523, height=21, width=74)
SoundsUsername2.configure(activebackground="#f9f9f9")
SoundsUsername2.configure(anchor='w')
SoundsUsername2.configure(background="#d9d9d9", cursor="@AdditionalCursors/pointer.cur")
SoundsUsername2.configure(compound='left')
SoundsUsername2.configure(font="-family {Segoe UI} -size 9 -underline 1")
SoundsUsername2.configure(foreground="#5662eb")
SoundsUsername2.configure(text='''Kastenfrosch''')

ImagesVect = tk.Label(top)
ImagesVect.place(relx=0.121, rely=0.569, height=21, width=214)
ImagesVect.configure(activebackground="#f9f9f9")
ImagesVect.configure(anchor='w')
ImagesVect.configure(background="#d9d9d9")
ImagesVect.configure(compound='left')
ImagesVect.configure(disabledforeground="#a3a3a3")
ImagesVect.configure(foreground="#000000")
ImagesVect.configure(highlightbackground="#d9d9d9")
ImagesVect.configure(highlightcolor="black")
ImagesVect.configure(text='''→ Images Vectorielles :''')

ImageWebsite = tk.Label(top)
ImageWebsite.place(relx=0.37, rely=0.569, height=21, width=54)
ImageWebsite.configure(activebackground="#f9f9f9")
ImageWebsite.configure(anchor='w')
ImageWebsite.configure(background="#d9d9d9", cursor="@AdditionalCursors/pointer.cur")
ImageWebsite.configure(compound='left')
ImageWebsite.configure(font="-family {Segoe UI} -size 9 -underline 1")
ImageWebsite.configure(foreground="#5662eb")
ImageWebsite.configure(text='''Flaticon''')

InfRelDevs = tk.Label(top)
InfRelDevs.place(relx=0.04, rely=0.683, height=21, width=324)
InfRelDevs.configure(activebackground="#f9f9f9")
InfRelDevs.configure(anchor='w')
InfRelDevs.configure(background="#d9d9d9")
InfRelDevs.configure(compound='left')
InfRelDevs.configure(disabledforeground="#a3a3a3")
InfRelDevs.configure(foreground="#000000")
InfRelDevs.configure(highlightbackground="#d9d9d9")
InfRelDevs.configure(highlightcolor="black")
InfRelDevs.configure(text='''Nous contacter''')

TitleSepContentRelDev = ttk.Separator(top)
TitleSepContentRelDev.place(relx=0.046, rely=0.747, relwidth=0.788)

DonateButton = tk.Button(top)
DonateButton.place(relx=0.119, rely=0.91, height=35, width=162)
DonateButton.configure(activebackground="#d9d9d9", cursor="@AdditionalCursors/pointer.cur")
DonateButton.configure(activeforeground="black")
DonateButton.configure(background="#d9d9d9")
DonateButton.configure(compound='left', relief="flat", bd=0, image=payp)
DonateButton.configure(foreground="#000000")
DonateButton.configure(pady="0")

Email1 = tk.Label(top)
Email1.place(relx=0.156, rely=0.802, height=21, width=154)
Email1.configure(activebackground="#f9f9f9")
Email1.configure(anchor='w')
Email1.configure(background="#d9d9d9", cursor="@AdditionalCursors/pointer.cur")
Email1.configure(compound='left')
Email1.configure(font="-family {Segoe UI} -size 9 -underline 1")
Email1.configure(foreground="#5662eb")
Email1.configure(text='''labarbe.leo2308@gmail.com''')

GmailIcon = tk.Label(top)
GmailIcon.place(relx=0.063, rely=0.81, height=36, width=36)
GmailIcon.configure(activebackground="#f9f9f9")
GmailIcon.configure(anchor='w')
GmailIcon.configure(background="#d9d9d9", image=mail)
GmailIcon.configure(compound='left')
GmailIcon.configure(relief=None)
GmailIcon.configure(text=None)

Email2 = tk.Label(top)
Email2.place(relx=0.156, rely=0.838, height=21, width=174)
Email2.configure(activebackground="#f9f9f9")
Email2.configure(anchor='w')
Email2.configure(background="#d9d9d9", cursor="@AdditionalCursors/pointer.cur")
Email2.configure(compound='left')
Email2.configure(font="-family {Segoe UI} -size 9 -underline 1")
Email2.configure(foreground="#5662eb")
Email2.configure(text='''labarbe.leo.scolaire@gmail.com''')

InstaIcon = tk.Label(top)
InstaIcon.place(relx=0.846, rely=0.792, height=36, width=36)
InstaIcon.configure(activebackground="#f9f9f9")
InstaIcon.configure(anchor='w')
InstaIcon.configure(background="#d9d9d9", image=inst)
InstaIcon.configure(compound='left')
InstaIcon.configure(foreground="#000000")
InstaIcon.configure(relief=None)
InstaIcon.configure(text=None)

InstaUsername = tk.Label(top)
InstaUsername.place(relx=0.642, rely=0.804, height=21, width=94)
InstaUsername.configure(activebackground="#f9f9f9")
InstaUsername.configure(anchor='w')
InstaUsername.configure(background="#d9d9d9", cursor="@AdditionalCursors/pointer.cur")
InstaUsername.configure(compound='left')
InstaUsername.configure(font="-family {Segoe UI} -size 9 -underline 1")
InstaUsername.configure(foreground="#5662eb")
InstaUsername.configure(text='''deltamercenary_''')

SnapIcon = tk.Label(top)
SnapIcon.place(relx=0.648, rely=0.89, height=36, width=36)
SnapIcon.configure(activebackground="#f9f9f9")
SnapIcon.configure(anchor='w')
SnapIcon.configure(background="#d9d9d9", image=snap)
SnapIcon.configure(compound='left')
SnapIcon.configure(foreground="#000000")
SnapIcon.configure(relief=None)
SnapIcon.configure(text=None)

SnapUsername = tk.Label(top)
SnapUsername.place(relx=0.743, rely=0.898, height=21, width=94)
SnapUsername.configure(anchor='w')
SnapUsername.configure(background="#d9d9d9", fg="#5662eb", cursor="@AdditionalCursors/pointer.cur")
SnapUsername.configure(font="-family {Segoe UI} -size 9 -underline 1")
SnapUsername.configure(text='''deltamercenary''')

PartSepVerticalDev = ttk.Separator(top)
PartSepVerticalDev.place(relx=0.566, rely=0.798,relheight=0.16)
PartSepVerticalDev.configure(orient="vertical")

top.mainloop()