#############################################################################
# Generated by PAGE version 7.6
#  in conjunction with Tcl version 8.6
#  Apr 16, 2023 03:43:01 PM CEST  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
}
vTcl:create_project_images $image_list   ;# In image.tcl

if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) black
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m47" -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 524x276+305+151
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1284 701
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    set toptitle "À Propos"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    button "$top.but47" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 
    vTcl:DefineAlias "$top.but47" "PayPal" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    vTcl:copy_lock $top.but47
    ttk::separator "$top.tSe48"
    vTcl:DefineAlias "$top.tSe48" "TSeparator1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    menu "$top.m47" \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background $vTcl(actual_gui_menu_bg) \
        -font "TkMenuFont" -foreground $vTcl(actual_gui_menu_fg) -tearoff 0 
### SPOT dump_widget_opt A
    button "$top.but48" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Button" 
    vTcl:DefineAlias "$top.but48" "GitHub" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    vTcl:copy_lock $top.but48
    button "$top.but50" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Button" 
    vTcl:DefineAlias "$top.but50" "Snapchat" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    vTcl:copy_lock $top.but50
    button "$top.but51" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Button" 
    vTcl:DefineAlias "$top.but51" "Discord" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    vTcl:copy_lock $top.but51
    button "$top.but55" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Button" 
    vTcl:DefineAlias "$top.but55" "Gmail" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    vTcl:copy_lock $top.but55
    label "$top.lab48" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 \
        -font "-family {Yu Gothic UI} -size 9 -weight normal -slant roman -underline 0 -overstrike 0" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "AutoBulletin est une application permettant au professeur l'utilisant de générer" 
    vTcl:DefineAlias "$top.lab48" "PresentationPt1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    vTcl:copy_lock $top.lab48
    label "$top.lab49" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 \
        -font "-family {Yu Gothic UI} -size 9 -weight normal -slant roman -underline 0 -overstrike 0" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "et d'écrire une appréciation sur le bulletin Pronote™ de l'élève." 
    vTcl:DefineAlias "$top.lab49" "PresentationPt2" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    vTcl:copy_lock $top.lab49
    frame "$top.fra50" \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 105 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 215 
    vTcl:DefineAlias "$top.fra50" "InfoFrame" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    set site_3_0 $top.fra50
    label "$site_3_0.lab52" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 \
        -font "-family {Yu Gothic UI} -size 9 -weight normal -slant roman -underline 0 -overstrike 0" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "Informations" 
    vTcl:DefineAlias "$site_3_0.lab52" "InfoLabel" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    vTcl:copy_lock $site_3_0.lab52
    label "$site_3_0.lab53" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief groove -text "→ Python 3.10.8" 
    vTcl:DefineAlias "$site_3_0.lab53" "PythonVerLabelGrv" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    vTcl:copy_lock $site_3_0.lab53
    label "$site_3_0.lab57" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief groove -text "→ GitHub du projet" 
    vTcl:DefineAlias "$site_3_0.lab57" "GitPrjLabelGrv" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    vTcl:copy_lock $site_3_0.lab57
    label "$site_3_0.lab60" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "→ Licence" 
    vTcl:DefineAlias "$site_3_0.lab60" "LicenceLabelFlt" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    vTcl:copy_lock $site_3_0.lab60
    place $site_3_0.lab52 \
        -in $site_3_0 -x 0 -relx 0.163 -y 0 -rely 0.076 -width 0 \
        -relwidth 0.67 -height 0 -relheight 0.2 -anchor nw -bordermode ignore 
    place $site_3_0.lab53 \
        -in $site_3_0 -x 0 -relx -0.023 -y 0 -rely 0.352 -width 0 \
        -relwidth 0.67 -height 0 -relheight 0.2 -anchor nw -bordermode ignore 
    place $site_3_0.lab57 \
        -in $site_3_0 -x 0 -relx -0.023 -y 0 -rely 0.705 -width 0 \
        -relwidth 0.67 -height 0 -relheight 0.2 -anchor nw -bordermode ignore 
    place $site_3_0.lab60 \
        -in $site_3_0 -x 0 -relx -0.023 -y 0 -rely 0.533 -width 0 \
        -relwidth 0.67 -height 0 -relheight 0.2 -anchor nw -bordermode ignore 
    vTcl:copy_lock $top.fra50
    frame "$top.fra51" \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 105 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 215 
    vTcl:DefineAlias "$top.fra51" "Frame1_1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    set site_3_0 $top.fra51
    button "$site_3_0.but55" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -relief groove 
    vTcl:DefineAlias "$site_3_0.but55" "Button1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    place $site_3_0.but55 \
        -in $site_3_0 -x 0 -relx 0.107 -y 0 -rely 0.667 -width 167 \
        -relwidth 0 -height 24 -relheight 0 -anchor nw -bordermode ignore 
    label "$top.lab50" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief groove -text "LABARBE Léo, Mr Imloul ←" 
    vTcl:DefineAlias "$top.lab50" "OutsFrmName" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    vTcl:copy_lock $top.lab50
    label "$top.lab51" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief groove -text "→ labarbe.leo2308@gmail.com" 
    vTcl:DefineAlias "$top.lab51" "OutsFrmMail" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    vTcl:copy_lock $top.lab51
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.but47 \
        -in $top -x 0 -relx 0.405 -y 0 -rely 0.812 -width 100 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $top.tSe48 \
        -in $top -x 0 -relx 0.309 -y 0 -rely 0.728 -width 0 -relwidth 0.382 \
        -height 0 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but48 \
        -in $top -x 0 -relx 0.313 -y 0 -rely 0.808 -width 32 -relwidth 0 \
        -height 32 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but50 \
        -in $top -x 0 -relx 0.221 -y 0 -rely 0.808 -width 32 -relwidth 0 \
        -height 32 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but51 \
        -in $top -x 0 -relx 0.628 -y 0 -rely 0.808 -width 32 -relwidth 0 \
        -height 32 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but55 \
        -in $top -x 0 -relx 0.719 -y 0 -rely 0.808 -width 32 -relwidth 0 \
        -height 32 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab48 \
        -in $top -x 0 -relx 0.086 -y 0 -rely 0.076 -width 0 -relwidth 0.828 \
        -height 0 -relheight 0.076 -anchor nw -bordermode ignore 
    place $top.lab49 \
        -in $top -x 0 -relx 0.086 -y 0 -rely 0.145 -width 0 -relwidth 0.828 \
        -height 0 -relheight 0.076 -anchor nw -bordermode ignore 
    place $top.fra50 \
        -in $top -x 0 -relx 0.086 -y 0 -rely 0.272 -width 0 -relwidth 0.41 \
        -height 0 -relheight 0.38 -anchor nw -bordermode ignore 
    place $top.fra51 \
        -in $top -x 0 -relx 0.504 -y 0 -rely 0.272 -width 0 -relwidth 0.41 \
        -height 0 -relheight 0.38 -anchor nw -bordermode ignore 
    place $top.lab50 \
        -in $top -x 0 -relx 0.599 -y 0 -rely 0.308 -width 0 -relwidth 0.332 \
        -height 0 -relheight 0.076 -anchor nw -bordermode ignore 
    place $top.lab51 \
        -in $top -x 0 -relx 0.5 -y 0 -rely 0.399 -width 0 -relwidth 0.332 \
        -height 0 -relheight 0.076 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

