#############################################################################
# Generated by PAGE version 7.6
#  in conjunction with Tcl version 8.6
#  Apr 17, 2023 04:37:37 PM CEST  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
}
vTcl:create_project_images $image_list   ;# In image.tcl

if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) black
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 495x501+362+104
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1284 701
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    set toptitle "À Propos"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    ttk::style configure Label -background $vTcl(actual_gui_bg)
    ttk::style configure Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure Label -font "$vTcl(actual_gui_font_dft_desc)"
    label "$top.lab47" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "Informations relatives à l'application" 
    vTcl:DefineAlias "$top.lab47" "InfRelAppLabel" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure TSeparator -background $vTcl(actual_gui_bg)
    ttk::style configure TSeparator -foreground $vTcl(actual_gui_fg)
    ttk::style configure TSeparator -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::separator "$top.tSe48"
    vTcl:DefineAlias "$top.tSe48" "TitleSepContentRelApp" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Label -background $vTcl(actual_gui_bg)
    ttk::style configure Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure Label -font "$vTcl(actual_gui_font_dft_desc)"
    label "$top.lab49" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief groove -text "Label" 
    vTcl:DefineAlias "$top.lab49" "AppLogoContainer" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Label -background $vTcl(actual_gui_bg)
    ttk::style configure Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure Label -font "$vTcl(actual_gui_font_dft_desc)"
    label "$top.lab50" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 \
        -font "-family {Yu Gothic UI} -size 11 -weight bold -slant roman -underline 0 -overstrike 0" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "AutoBulletin" 
    vTcl:DefineAlias "$top.lab50" "AppName" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Label -background $vTcl(actual_gui_bg)
    ttk::style configure Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure Label -font "$vTcl(actual_gui_font_dft_desc)"
    label "$top.lab51" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "B.0.2" 
    vTcl:DefineAlias "$top.lab51" "AppVers" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Label -background $vTcl(actual_gui_bg)
    ttk::style configure Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure Label -font "$vTcl(actual_gui_font_dft_desc)"
    label "$top.lab52" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "© LABARBE Léo, Mr Imloul" 
    vTcl:DefineAlias "$top.lab52" "AppCopyrights" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Label -background $vTcl(actual_gui_bg)
    ttk::style configure Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure Label -font "$vTcl(actual_gui_font_dft_desc)"
    label "$top.lab53" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "Remerciments" 
    vTcl:DefineAlias "$top.lab53" "ThxLabel" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Label -background $vTcl(actual_gui_bg)
    ttk::style configure Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure Label -font "$vTcl(actual_gui_font_dft_desc)"
    label "$top.lab54" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "→ Curseurs :" 
    vTcl:DefineAlias "$top.lab54" "Cursors" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Label -background $vTcl(actual_gui_bg)
    ttk::style configure Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure Label -font "$vTcl(actual_gui_font_dft_desc)"
    label "$top.lab48" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9 -weight normal -slant roman -underline 1 -overstrike 0" \
        -foreground #5662eb -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text "FlynMaker49" 
    vTcl:DefineAlias "$top.lab48" "CursorsUsername" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Label -background $vTcl(actual_gui_bg)
    ttk::style configure Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure Label -font "$vTcl(actual_gui_font_dft_desc)"
    label "$top.lab55" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "→ Sons :" 
    vTcl:DefineAlias "$top.lab55" "Sounds" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Label -background $vTcl(actual_gui_bg)
    ttk::style configure Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure Label -font "$vTcl(actual_gui_font_dft_desc)"
    label "$top.lab56" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9 -weight normal -slant roman -underline 1 -overstrike 0" \
        -foreground #5662eb -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text "Leszek_Szary" 
    vTcl:DefineAlias "$top.lab56" "SoundsUsername1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Label -background $vTcl(actual_gui_bg)
    ttk::style configure Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure Label -font "$vTcl(actual_gui_font_dft_desc)"
    label "$top.lab57" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9 -weight normal -slant roman -underline 1 -overstrike 0" \
        -foreground #5662eb -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text "Kastenfrosch" 
    vTcl:DefineAlias "$top.lab57" "SoundsUsername2" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Label -background $vTcl(actual_gui_bg)
    ttk::style configure Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure Label -font "$vTcl(actual_gui_font_dft_desc)"
    label "$top.lab58" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "→ Images Vectorielles :" 
    vTcl:DefineAlias "$top.lab58" "ImagesVect" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Label -background $vTcl(actual_gui_bg)
    ttk::style configure Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure Label -font "$vTcl(actual_gui_font_dft_desc)"
    label "$top.lab59" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9 -weight normal -slant roman -underline 1 -overstrike 0" \
        -foreground #5662eb -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text "Flaticon" 
    vTcl:DefineAlias "$top.lab59" "ImageWebsite" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Label -background $vTcl(actual_gui_bg)
    ttk::style configure Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure Label -font "$vTcl(actual_gui_font_dft_desc)"
    label "$top.lab61" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "Nous contacter" 
    vTcl:DefineAlias "$top.lab61" "InfRelDevs" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure TSeparator -background $vTcl(actual_gui_bg)
    ttk::style configure TSeparator -foreground $vTcl(actual_gui_fg)
    ttk::style configure TSeparator -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::separator "$top.tSe62"
    vTcl:DefineAlias "$top.tSe62" "TitleSepContentRelDev" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Button -background $vTcl(actual_gui_bg)
    ttk::style configure Button -foreground $vTcl(actual_gui_fg)
    ttk::style configure Button -font "$vTcl(actual_gui_font_dft_desc)"
    button "$top.but47" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 
    vTcl:DefineAlias "$top.but47" "DonateButton" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Label -background $vTcl(actual_gui_bg)
    ttk::style configure Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure Label -font "$vTcl(actual_gui_font_dft_desc)"
    label "$top.lab62" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9 -weight normal -slant roman -underline 1 -overstrike 0" \
        -foreground #5662eb -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text "labarbe.leo2308@gmail.com" 
    vTcl:DefineAlias "$top.lab62" "Email1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Label -background $vTcl(actual_gui_bg)
    ttk::style configure Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure Label -font "$vTcl(actual_gui_font_dft_desc)"
    label "$top.lab63" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief groove -text "Label" 
    vTcl:DefineAlias "$top.lab63" "GmailIcon" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Label -background $vTcl(actual_gui_bg)
    ttk::style configure Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure Label -font "$vTcl(actual_gui_font_dft_desc)"
    label "$top.lab60" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9 -weight normal -slant roman -underline 1 -overstrike 0" \
        -foreground #5662eb -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text "labarbe.leo.scolaire@gmail.com" 
    vTcl:DefineAlias "$top.lab60" "Email2" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Label -background $vTcl(actual_gui_bg)
    ttk::style configure Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure Label -font "$vTcl(actual_gui_font_dft_desc)"
    label "$top.lab64" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief groove -text "Label" 
    vTcl:DefineAlias "$top.lab64" "InstaIcon" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Label -background $vTcl(actual_gui_bg)
    ttk::style configure Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure Label -font "$vTcl(actual_gui_font_dft_desc)"
    label "$top.lab66" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9 -weight normal -slant roman -underline 1 -overstrike 0" \
        -foreground #5662eb -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text "deltamercenary_" 
    vTcl:DefineAlias "$top.lab66" "InstaUsername" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Label -background $vTcl(actual_gui_bg)
    ttk::style configure Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure Label -font "$vTcl(actual_gui_font_dft_desc)"
    label "$top.lab68" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief groove -text "Label" 
    vTcl:DefineAlias "$top.lab68" "SnapIcon" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Label -background $vTcl(actual_gui_bg)
    ttk::style configure Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure Label -font "$vTcl(actual_gui_font_dft_desc)"
    label "$top.lab69" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9 -weight normal -slant roman -underline 1 -overstrike 0" \
        -foreground #5662eb -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text "deltamercenary" 
    vTcl:DefineAlias "$top.lab69" "SnapUsername" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure TSeparator -background $vTcl(actual_gui_bg)
    ttk::style configure TSeparator -foreground $vTcl(actual_gui_fg)
    ttk::style configure TSeparator -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::separator "$top.tSe70" \
        -orient vertical 
    vTcl:DefineAlias "$top.tSe70" "PartSepVerticalDev" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab47 \
        -in $top -x 0 -relx 0.04 -y 0 -rely 0.026 -width 0 -relwidth 0.655 \
        -height 0 -relheight 0.042 -anchor nw -bordermode ignore 
    place $top.tSe48 \
        -in $top -x 0 -relx 0.046 -y 0 -rely 0.092 -width 0 -relwidth 0.788 \
        -height 0 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab49 \
        -in $top -x 0 -relx 0.069 -y 0 -rely 0.132 -width 0 -relwidth 0.21 \
        -height 0 -relheight 0.208 -anchor nw -bordermode ignore 
    place $top.lab50 \
        -in $top -x 0 -relx 0.303 -y 0 -rely 0.174 -width 0 -relwidth 0.412 \
        -height 0 -relheight 0.042 -anchor nw -bordermode ignore 
    place $top.lab51 \
        -in $top -x 0 -relx 0.301 -y 0 -rely 0.212 -width 0 -relwidth 0.17 \
        -height 0 -relheight 0.042 -anchor nw -bordermode ignore 
    place $top.lab52 \
        -in $top -x 0 -relx 0.299 -y 0 -rely 0.251 -width 0 -relwidth 0.331 \
        -height 0 -relheight 0.042 -anchor nw -bordermode ignore 
    place $top.lab53 \
        -in $top -x 0 -relx 0.063 -y 0 -rely 0.391 -width 0 -relwidth 0.432 \
        -height 0 -relheight 0.042 -anchor nw -bordermode ignore 
    place $top.lab54 \
        -in $top -x 0 -relx 0.121 -y 0 -rely 0.441 -width 0 -relwidth 0.432 \
        -height 0 -relheight 0.042 -anchor nw -bordermode ignore 
    place $top.lab48 \
        -in $top -x 0 -relx 0.263 -y 0 -rely 0.441 -width 0 -relwidth 0.149 \
        -height 0 -relheight 0.042 -anchor nw -bordermode ignore 
    place $top.lab55 \
        -in $top -x 0 -relx 0.121 -y 0 -rely 0.487 -width 0 -relwidth 0.432 \
        -height 0 -relheight 0.042 -anchor nw -bordermode ignore 
    place $top.lab56 \
        -in $top -x 0 -relx 0.218 -y 0 -rely 0.487 -width 0 -relwidth 0.149 \
        -height 0 -relheight 0.042 -anchor nw -bordermode ignore 
    place $top.lab57 \
        -in $top -x 0 -relx 0.218 -y 0 -rely 0.523 -width 0 -relwidth 0.149 \
        -height 0 -relheight 0.042 -anchor nw -bordermode ignore 
    place $top.lab58 \
        -in $top -x 0 -relx 0.121 -y 0 -rely 0.569 -width 0 -relwidth 0.432 \
        -height 0 -relheight 0.042 -anchor nw -bordermode ignore 
    place $top.lab59 \
        -in $top -x 0 -relx 0.37 -y 0 -rely 0.569 -width 0 -relwidth 0.109 \
        -height 0 -relheight 0.042 -anchor nw -bordermode ignore 
    place $top.lab61 \
        -in $top -x 0 -relx 0.04 -y 0 -rely 0.683 -width 0 -relwidth 0.655 \
        -height 0 -relheight 0.042 -anchor nw -bordermode ignore 
    place $top.tSe62 \
        -in $top -x 0 -relx 0.046 -y 0 -rely 0.747 -width 0 -relwidth 0.788 \
        -height 0 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but47 \
        -in $top -x 0 -relx 0.119 -y 0 -rely 0.91 -width 162 -relwidth 0 \
        -height 35 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab62 \
        -in $top -x 0 -relx 0.156 -y 0 -rely 0.802 -width 0 -relwidth 0.311 \
        -height 0 -relheight 0.042 -anchor nw -bordermode ignore 
    place $top.lab63 \
        -in $top -x 0 -relx 0.063 -y 0 -rely 0.81 -width 0 -relwidth 0.073 \
        -height 0 -relheight 0.072 -anchor nw -bordermode ignore 
    place $top.lab60 \
        -in $top -x 0 -relx 0.156 -y 0 -rely 0.838 -width 0 -relwidth 0.352 \
        -height 0 -relheight 0.042 -anchor nw -bordermode ignore 
    place $top.lab64 \
        -in $top -x 0 -relx 0.846 -y 0 -rely 0.792 -width 0 -relwidth 0.073 \
        -height 0 -relheight 0.072 -anchor nw -bordermode ignore 
    place $top.lab66 \
        -in $top -x 0 -relx 0.642 -y 0 -rely 0.804 -width 0 -relwidth 0.19 \
        -height 0 -relheight 0.042 -anchor nw -bordermode ignore 
    place $top.lab68 \
        -in $top -x 0 -relx 0.648 -y 0 -rely 0.89 -width 0 -relwidth 0.073 \
        -height 0 -relheight 0.072 -anchor nw -bordermode ignore 
    place $top.lab69 \
        -in $top -x 0 -relx 0.743 -y 0 -rely 0.898 -width 0 -relwidth 0.19 \
        -height 0 -relheight 0.042 -anchor nw -bordermode ignore 
    place $top.tSe70 \
        -in $top -x 0 -relx 0.566 -y 0 -rely 0.798 -width 0 -relwidth 0.004 \
        -height 0 -relheight 0.16 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

